# Generated by Django 4.2.7 on 2023-12-12 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='adsBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_banner', models.ImageField(default='banner.png', upload_to='banner/')),
            ],
        ),
    ]
