# Generated by Django 4.2.7 on 2023-12-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_whosbanner_delete_adsbanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='banner.png', upload_to='banner/')),
            ],
        ),
    ]
